easyGoals = [
"Obtain the Udjat Eye|eyeball|",
"Break a mattock|head",
"Complete the entire tutorial|15coins|ALL 3 stages must be completed.",
"Rescue a sloth|poison",
"Convert one Ruby, one Sapphire, and one Emerald into diamonds on the same level|fly|Simple enough, all 3 must be converted on the same level.",
"Spawn a spider in the Ice Caves|satisfySlot|This can be through the use of a Kali Altar, or from a pot.",
"Get Crushed|asteroidBoss|Either from Olmec, a push block, or a thwomp",
"Win on a Wheel of Fortune|angelRoom|You can win regularly, the actual prize, or the jackpot.",
"Purchase a Hired Help|suitCard|This doesn't mean you have to use him.",
"Rescue a crystal or golden idol|gurdy",
"Die from the ghost|bombBeggar",
"Kill a Rat, Mini Blue Frog, Penguin, or Cricket|meatSphere",
"Obtain 100k gold in a single seed|55coins",
"48 Bombs|20bombs",
"Shoot a gun.|greenChamp|Plasma cannon, Freeze Ray, or shotgun.",
"Obtain an eggplant|satisfySacRoom",
"Get attacked by a monkey|teleportBoss",
"Purchase a Mystery Box|unknownBox",
"Take 1 damage from a Snail Bubble|snotBubble|Shortcuts are allowed.",
]

mediumGoals = [
"Win a deathmatch|fullClearXL|Must be against AI",
"Exit the Worm|permaFlight|You can use the jungle or ice caves shortcut.",
"72 bombs|100combinedThings|",
"15 ropes|permaMap",
"Sacrifice something that is alive that is not a Damsel|3orbitals|For example, a K-O'd scorpion, or a K-O'd Caveman.",
"Get invigoration from Kali|healthFollower|This is the reward from Kali that comes after the Kapala",
"Get the Ball and Chain|2shootingFollowers|You are allowed to get rid of it once you have it.",
"Summon a Golden or Platinum Monkey|3devilDeals|To summon either, sacrifice a golden or crystal idol to Kali",
"Defeat Olmec|bossChallengeRoom|The temple shortcut is allowed.",
"Kill the Queen Bee|3superSecret",
"Obtain 200k gold in a single seed|destroyGoldPoop",
"Get a Jetpack|maxDamageBars",
"Steal the Damsel from a Kissing Booth, and bring her to the exit of that level|maxTearsBars",
"Obtain 21 ropes|6rangeBars",
"Rescue a crystal idol|6speedBars|Obviously this can only be done on a Restless Dead level feeling.",
"Obtain a Freeze Ray from a mammoth in the Ice Caves|beam|You don't have to pick it up, you just have to get a mammoth to drop one.",
"Kill yourself with Anubis' Scepter|satisfyBeggar",
"Uncover the shotgun in a Restless Dead level|7redHearts|It can be uncovered beneath the ASH tombstone",
"Get to 8 health|12health",
"Raid a vault|satisfyBank|The shopkeeper from inside the vault must be killed.",
"Turn an orange frog into a blue one|2guppy|This can be done by making an orange frog jump into pools of water.",
]

hardGoals = [
"Defeat Yama|blueBaby",
"Obtain Vlad's Cape|heartNoShooting|Vlad must be killed, and the cape must be put on for a few seconds.",
"Kill 'Ol Bitey|heartNoTreasure|You're welcome, Pib ;)",
"Kill the alien queen in the Mothership|heartNoContainers",
"Kill all Giant Spiders on a Skin is Crawling level|satanNoChest|This includes any found outside of the centralized cocoons.",
"Take a picture of the Ghost|satanNoBombs|Use the camera.",
"Kill Anubis II|satanNoShop",
"Kill ALL the shopkeepers in the Black Market|fartOnSatan",
"Obtain the Crysknife|fullClearSheol",
"Complete the Mines without collecting any gold|isaacNoChest",
"12 total health|isaacNoBombs",
"Teleport into the Moai|isaacNoShop",
"Telefrag ANY enemy|peeIsaac",
"Complete a level in less than 5 seconds|fullClearCath|Teleporter is recommended",
"Kill the Black Knight in the Castle|noHitWomb2|To enter the castle, you must blow up underneath the crowned grave in a Restless Dead jungle",
"Get knocked out by a monkey|noHitCaves",
];


var exclusions = [
];
