easyGoals = [
"Obtain the Udjat Eye|eyeball|",
"Break a mattock|head",
"Complete the entire tutorial|15coins|ALL 3 stages must be completed.",
"Rescue a sloth|poison",
"Convert one Ruby, one Sapphire, and one Emerald into diamonds on the same level|fly|Simple enough, all 3 must be converted on the same level.",
"Spawn a spider in the Ice Caves|satisfySlot|This can be through the use of a Kali Altar, or from a pot.",
"Get Crushed|asteroidBoss|Either from Olmec, a push block, or a thwomp",
"Win on a Wheel of Fortune|angelRoom|You can win regularly, the actual prize, or the jackpot.",
"Purchase a Hired Help|suitCard|This doesn't mean you have to use him.",
"Rescue a crystal or golden idol|gurdy",
"Die from the ghost|bombBeggar",
"Kill a Rat, Mini Blue Frog, Penguin, or Cricket|meatSphere",
"Obtain 100k gold in a single run|55coins",
"48 Bombs|20bombs",
"Shoot a gun.|greenChamp|Plasma cannon, Freeze Ray, or shotgun.",
"Obtain an eggplant|satisfySacRoom|",
"Get attacked by a monkey|teleportBoss",
"Purchase a Mystery Box|unknownBox",
]

mediumGoals = [
"Win a deathmatch|fullClearXL|Must be against AI",
"Enter the Worm|permaFlight|You can use the jungle shortcut.",
"72 bombs|100combinedThings|",
"15 ropes|permaMap",
"Sacrifice something that is alive that is not a Damsel|3orbitals|For example, a K-O'd scorpion, or a K-O'd Caveman.",
"Get invigoration from Kali|healthFollower|This is the reward from Kali that comes after the Kapala",
"2 Items That Move and Shoot|2shootingFollowers|Any baby follower, meat sphere, etc",
"3 Devil Deals|3devilDeals|Must be on a single run. Finding devil items outside a deal room doesn't count",
"Clear a Boss Challenge Room|bossChallengeRoom|These are the rooms you have to be at 1hp or less to enter",
"Enter 3 Super Secret Rooms|3superSecret|Must be on a single run",
"Destroy a Golden Poop|destroyGoldPoop",
"Permanent 6 Damage Bars|maxDamageBars|Sword stat.",
"Max Tears Up Bars|maxTearsBars|Arrow stat",
"4 Range Bars|6rangeBars|Bow stat",
"6 Speed Bars|6speedBars|Foot stat",
"Shoot a Beam or Laser|beam|Brimstone, Shoop da whoop, Tech 1, Tech 2, Robo baby",
"Satisfy a Normal Beggar|satisfyBeggar|Make it disappear with coins",
"7 Red Heart Containers|7redHearts|Empty ones count",
"12 Total Health Containers (any color)|12health|Empty ones count",
"Satisfy a Blood Bank|satisfyBank|Obtain IV Bag or Blood Bag from it",
"2 Guppy Items|2guppy|Head, Tail, Paw, Dead Cat. Hairball doesn't count",
"Skatole|skatole",
"Kill a Super or Ultra Sin Miniboss|specialSin",
"Cut Something|cutSomething|Knife, Dagger, Shears, Blood rights, Razor blade",
"Kill a Boss Without Shooting or Space Items or Bombs|bossOrbitals|For example, with orbitals",
"Gold Key|goldKey|Dad's Key doesn't count",
"Beat Heart Without Ever Using a Space Item|killHeartNoSpace",
"Beat Heart With 1 Heart|heart1heart|Start the heart fight at 1 or less health and don't go above 1 until it dies. Blue and white hearts count as health.",
"Resurrection|resurrection|Die with 1UP, Ankh, Dead Cat",
]

hardGoals = [
"Beat Blue Baby|blueBaby",
"Beat Heart Without Shooting or Space Items During Fight|heartNoShooting|For example, with bombs and orbitals. Anything that uses the shooting controls is shooting.",
"Beat Heart Without Getting an Item from a Treasure Room|heartNoTreasure|From Basement to Heart",
"Beat Heart Without Ever Gaining Red Heart Containers|heartNoContainers|From Basement to Heart",
"Beat Satan Without Opening any Chests|satanNoChest|From Basement to Satan",
"Beat Satan Without Using any Bombs on the Run|satanNoBombs|From Basement to Satan. If you get a room that needs bombs to progress then you're screwed.",
"Beat Satan Without Shopping|satanNoShop|From Basement to Satan. Gambling is not shopping.",
"Fart on Satan|fartOnSatan|Needs to actually poison him. Phase 1 of the fight doesn't count.",
"Full Clear Sheol|fullClearSheol",
"Beat Isaac Without Opening any Chests|isaacNoChest|From Basement to Isaac",
"Beat Isaac Without Using any Bombs on the Run|isaacNoBombs|From Basement to Isaac",
"Beat Isaac Without Shopping|isaacNoShop|From Basement to Isaac",
"Damage Isaac With Pee or Holy Water|peeIsaac|Isaac the boss, not Isaac the player character",
"Full Clear Cathedral|fullClearCath|All normal rooms and the boss",
"No Damage on Womb 2 or XL|noHitWomb2|Health can't go down for any reason. Forget me now gives a second chance",
"Full Clear and No Damage Caves 1 and 2 or XL|noHitCaves|All normal rooms and the boss. Health can't go down for any reason. Forget me now gives a second chance",
];


var exclusions = [
["fartOnSatan", "poison"],
["permaFlight", "fly"],
["satanNoBombs", "satanNoChest", "satanNoShop"],
["isaacNoBombs", "isaacNoChest", "isaacNoShop"],
["satanNoBombs", "isaacNoBombs"],
["satanNoChest", "isaacNoChest"],
["satanNoShop", "isaacNoShop"],
["meatSphere", "2shootingFollowers"],
["100combinedThings", "55coins"],
["noHitWomb2", "noHitCaves"],
];
